# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/sauhark@outlook.com/New Pipeline 2025-11-20 11:24")

# COMMAND ----------

df = spark.read.table('dltsauhar.source.orders')
display(df)